### ISSUE TITLE
MultiValueDictionary.Clone() do not clone inner HashSet value container

### ISSUE THREAD

**Issue by majerm** [SolutionsDesign/Algorithmia#12] opened 2022-08-18 13:12 UTC
I mean it is a bug, because it is inner implementation structure. In my case it was a problem. I did not create pull-request, because fix is breaking change.
In my version it is fixed like this:

```csharp
	public class MultiValueDictionary<...>

		private IEqualityComparer<TKey> _keyComparer;

                ....
		public MultiValueDictionary(IEqualityComparer<TKey> keyComparer, IEqualityComparer<TValue> valueComparer) : base(keyComparer)
		{
			_keyComparer = keyComparer;
			_valueComparer = valueComparer;
		}

		public MultiValueDictionary<TKey, TValue> Clone()
		{
			var clone = _keyComparer == null
				? new MultiValueDictionary<TKey, TValue>(_valueComparer)
				: new MultiValueDictionary<TKey, TValue>(_keyComparer, _valueComparer);
			foreach (var entry in this)
			{
				clone.Add(entry.Key, new HashSet<TValue>(entry.Value, _valueComparer));
			}
			return clone;
		}
                ....

```

**Comment by FransBouma** [comment] 2022-08-18 18:33
The codebase doesn't contain a SortedMultiValueDictionary... ? :) The Clone() method currently there does a memberwise clone, which will shallowcopy the contents of all members? Not sure why you'd do it this way?

**Comment by majerm** [comment] 2022-08-19 06:50
Sorry, its from my modification. It is in MultiValueDictionary.

My test with current version in nuget:

```csharp
using SD.Tools.Algorithmia.GeneralDataStructures;
using System;
using System.Collections.Generic;

namespace TestApp
{
    internal static class Program
    {
        class ModifiedMultiValueDictionary<TKey, TValue>: MultiValueDictionary<TKey, TValue>
        {
            public ModifiedMultiValueDictionary<TKey, TValue> Clone2()
            {
                var clone = new ModifiedMultiValueDictionary<TKey, TValue>();
                foreach (var entry in this)
                {
                    clone.Add(entry.Key, new HashSet<TValue>(entry.Value));
                }
                return clone;
            }
        }

        [STAThread]
        private static void Main()
        {
            var original = new MultiValueDictionary<string, string>();
            original.AddRange("test1", new string[] { "A", "B" });
            original.AddRange("test2", new string[] { "C", "D" });
            original.AddRange("test3", new string[] { "E", "F" });
            
            var clone = original.Clone();
            clone.Remove("test1");
            clone.Remove("test2", "D");
            original.Remove("test3", "F");

            System.Diagnostics.Debug.WriteLine(@"MultiValueDictionary ORIGINAL");
            foreach (var item in original)
            {
                System.Diagnostics.Debug.WriteLine($"{item.Key}: {String.Join(", ", item.Value)}");
            }
            System.Diagnostics.Debug.WriteLine(@"MultiValueDictionary CLONE");
            foreach (var item in clone)
            {
                System.Diagnostics.Debug.WriteLine($"{item.Key}: {String.Join(", ", item.Value)}");
            }

            var original2 = new ModifiedMultiValueDictionary<string, string>();
            original2.AddRange("test1", new string[] { "A", "B" });
            original2.AddRange("test2", new string[] { "C", "D" });
            original2.AddRange("test3", new string[] { "E", "F" });
            
            var clone2 = original2.Clone2();
            clone2.Remove("test1");
            clone2.Remove("test2", "D");
            original2.Remove("test3", "F");

            System.Diagnostics.Debug.WriteLine(@"ModifiedMultiValueDictionary ORIGINAL");
            foreach (var item in original2)
            {
                System.Diagnostics.Debug.WriteLine($"{item.Key}: {String.Join(", ", item.Value)}");
            }
            System.Diagnostics.Debug.WriteLine(@"ModifiedMultiValueDictionary CLONE");
            foreach (var item in clone2)
            {
                System.Diagnostics.Debug.WriteLine($"{item.Key}: {String.Join(", ", item.Value)}");
            }
        }
}
```

Output:
```
MultiValueDictionary ORIGINAL
test2: C
test3: E
MultiValueDictionary CLONE
test2: C
test3: E
ModifiedMultiValueDictionary ORIGINAL
test1: A, B
test2: C, D
test3: E
ModifiedMultiValueDictionary CLONE
test2: C
test3: E, F
```

I was expecting the second behavior, but mabye I am wrong. Feel free to close issue.

Anyway, thank you very much for the great library :)

**Comment by FransBouma** [comment] 2022-08-19 08:23
Hmm, to my knowledge the memberwise clone implemented in the original should give the same results for your modified dictionary too. But as it's a shallow clone, you might not want it for your purposes. (as it does a memberwise clone but not a deep copy)

As our code works as intended, I think I have to close this issue, sorry :) 

> Anyway, thank you very much for the great library :)

Thanks! :)

**Closed as completed by FransBouma** 2022-08-19 08:23 UTC
